@startuml

title Sequence diagram "Show requests"

actor User
boundary showRequests.jsp
boundary adminpage.jsp
participant FrontController
participant Command
participant ShowRequests
participant LogicFacade
participant RequestMapper
database Database

User -> adminpage.jsp : request
adminpage.jsp -> FrontController : doPost()
FrontController -> Command : showRequests()
Command -> ShowRequests : showRequests()
ShowRequests -> LogicFacade : showRequest()
LogicFacade -> RequestMapper : showRequest()
RequestMapper -> Database : executeUpdate()
Database -> RequestMapper : resultset
RequestMapper -> LogicFacade :
LogicFacade -> ShowRequests :
ShowRequests-> showRequests.jsp :
showRequests.jsp -> User : List of requests
ShowRequests -> showRequests.jsp : Failure (alternative flow)
showRequests.jsp -> User : Please try again!
@enduml
